olist_spark_profile:
  target: dev
  outputs:
    dev:
      type: spark
      # --- Extreme Resource Optimization for 4GB RAM ---
      # Why: 'session' method runs PySpark locally inside the dbt process itself.
      # It avoids running a heavy, permanent Thrift Server daemon, saving over 1GB of idle RAM.
      method: session
      schema: silver
      host: localhost
      # --- In-Session Spark Engine Tuning Parameters ---
      spark_configs:
        spark.master: "local[1]"
        spark.sql.shuffle.partitions: "1"
        spark.default.parallelism: "1"
        spark.driver.memory: "1g"
        
        # --- Apache Iceberg Catalog Integration ---
        spark.sql.sources.default: "iceberg"
        spark.sql.extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
        
        # Catalog Configs (Overriding default Hive Metastore with Iceberg)
        spark.sql.catalog.spark_catalog: "org.apache.iceberg.spark.SparkCatalog"
        spark.sql.catalog.spark_catalog.type: "hadoop"
        spark.sql.catalog.spark_catalog.warehouse: "gs://{{ env_var('GCS_BUCKET_NAME') }}/warehouse"
        
        # Inject GCS configs DIRECTLY into Iceberg Catalog specific namespace
        spark.sql.catalog.spark_catalog.hadoop.fs.gs.impl: "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
        spark.sql.catalog.spark_catalog.hadoop.google.cloud.auth.service.account.enable: "true"
        
        # Global GCS Configs
        spark.hadoop.fs.gs.impl: "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
        spark.hadoop.google.cloud.auth.service.account.enable: "true"